### ISSUE TITLE
signArbitraryData method produces invalid signature

### ISSUE THREAD

**Issue by goga-m** [EOSDAQ/keycat#7]
Greetings,

And thanks for making this great authenticator. 

It seems that when I am trying to use signArbitraryData method, the signature that is generated is invalid and belongs to a different pubkey (non-existent).

I' ll try to demonstrate the case with an example (using an account from the provided example), so that it would be easily reproduced:

```
const accountName = 'lebronjames2'
const pubKey = 'EOS8RdaZWEmwn87YewRS1qVaswh7DunG5mYX3GZCJFBJQcNqzc8pZ'
const wif = '5JFJ5irexsvkmLW892DN3LcZmUYoCHm4ES7XD4zGGL3Y4mvLVU2'
const sigMessage = 'test'

const keycat = new Keycat({
  blockchain: {
    name: 'eos-jungle',
    nodes: [
      'https://jungle2.cryptolions.io',
    ]
  }
})

keycat.account(accountName).signArbitraryData([sigMessage])
// Produces: SIG_K1_KXA61WTw51d1HfqBVARyEx6hrjLBN4SU3DQspJNSbZoeciR47ZyXK9uG2k45q6rUrDXv87zGrjh1YdWAMn9GB9qn6veAjX
```

Now when you try to verify the signature (using eosjs-ecc) somewhere else, it fails:
```
ecc.verify('SIG_K1_KXA61WTw51d1HfqBVARyEx6hrjLBN4SU3DQspJNSbZoeciR47ZyXK9uG2k45q6rUrDXv87zGrjh1YdWAMn9GB9qn6veAjX', sigMessage, pubKey)
// false
```

And if you try to recover the pubKey by the produced signature (using again eosjs-ecc), the  pubkey that is produced is: `EOS5NELdufi7CMU22qNUoCtFo2MZoj6RMuBpd93RopmwTtopDP4Hf`

```
ecc.recover('SIG_K1_KXA61WTw51d1HfqBVARyEx6hrjLBN4SU3DQspJNSbZoeciR47ZyXK9uG2k45q6rUrDXv87zGrjh1YdWAMn9GB9qn6veAjX', sigMessage)
// EOS5NELdufi7CMU22qNUoCtFo2MZoj6RMuBpd93RopmwTtopDP4Hf
```

When signing the message with eosjs-ecc, it produces the following signature which is succesfully verified:
```
ecc.sign(sigMessage, wif)
// Produces: SIG_K1_KmGPWYActCqUBu2uT7iZHeRNzTtXAH3hmN9pgJcNmU5FAHvbX4wYjmfesxRArHVnqpT5FrLDjGDMaLyRtuVnZrUm1gybEC
```

Any ideas on what could be responsible for this?

Thanks again!

**Comment by indegser-eosdaq** [comment]
Hi, Thanks for the issue.
We found the bug and it is currently fixed.
It was due to `JSON.stringify`ing of parameters inside our code. 
So example sigMessage `'test'` was changed to `"'test'"`.
You can try it again but with slight change of example code.

```javascript
const sigMessage = 'test'
const result = await keycat.account(...).signArbitraryData(sigMessage) // You don't have to wrap sigMessage inside array.
ecc.verify(result, sigMessage, pubKey) // true

```

**Comment by goga-m** [comment]
Works great now @indegser-eosdaq 
Thanks!
